[package]
name = "aemula"
version = "0.1.0"
authors = ["Tim Jones <tim@timjones.io>"]
edition = "2018"

[dependencies]
aemula_macros = { path = "macros" }
bitflags = "1.2.1"
minifb = "0.16"

[dev-dependencies]
file_diff = "1.0.0"
test-case = "1.0.0"