[package]
name = "aemula"
version = "0.1.0"
authors = ["Tim Jones <tim@timjones.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"

[dev-dependencies]
file_diff = "1.0.0"